name: Deploy Back

on:
  push:
#    branches:
#      - develop
jobs:
   build-api:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout
            uses: actions/checkout@v3
            with:
               fetch-depth: 0

         -  name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-1

         -  name: Amazon ECR "Login" Action for GitHub Actions
            uses: aws-actions/amazon-ecr-login@v1

         -  name: Build, tag, and push image to Amazon ECR
            env:
               ECR_REGISTRY: 171114599228.dkr.ecr.us-east-1.amazonaws.com
               ECR_REPOSITORY: grupo-l-api
               IMAGE_TAG: latest
            run: |
               docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./packages/api2/Dockerfile .
               docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

         -  name: Logout of Amazon ECR
            run: docker logout ${{ steps.login-ecr.outputs.registry }}